[package]
name = "idevice"
version = "0.1.0"
edition = "2021"

[dependencies]
plist = { version = "1.7" }
serde = { version = "1", features = ["derive"] }
thiserror = { version = "2" }
log = { version = "0.4" }
env_logger = { version = "0.11" }
openssl = { version = "0.10" }
