name: Build idevice for iOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build for iOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios, x86_64-apple-ios, aarch64-apple-ios-sim

      - name: Install dependencies
        run: |
          brew install libimobiledevice usbmuxd libplist
          echo "Setting environment variables for library paths..."
          echo "LIBRARY_PATH=/usr/local/opt/libimobiledevice/lib:/usr/local/opt/libusbmuxd/lib:/usr/local/opt/libplist/lib:$LIBRARY_PATH" >> $GITHUB_ENV
          echo "CPATH=/usr/local/opt/libimobiledevice/include:/usr/local/opt/libusbmuxd/include:/usr/local/opt/libplist/include:$CPATH" >> $GITHUB_ENV

      - name: Install cargo-lipo and cargo-xcode
        run: |
          cargo install cargo-lipo
          cargo install cargo-xcode

      - name: Build for iOS
        run: |
          cargo xcode
          cargo lipo --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: idevice-ios
          path: target/universal/release/libidevice.a
